spring:
  data:
    mongodb:
      host: localHost
      port: 27017
      database: taskTrackingDb
      auto-index-creation: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  user-init-file: userInit.csv
  board-init-file: boardInit.csv
  task-init-file: taskInit.csv
  comment-init-file: commentInit.csv