server:
  port: 0

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      host: localHost
      port: 27017
      database: taskTrackingDb
      auto-index-creation: true