server:
  port: 0

spring:
  data:
    mongodb:
      host: localHost
      port: 27017
      database: taskTrackingDb
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"